# Generated by Django 4.2.1 on 2023-05-17 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Employeetask',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=50, verbose_name='Task')),
                ('cat', models.IntegerField(choices=[(1, 'male'), (2, 'female')], verbose_name='Category')),
                ('contact', models.CharField(max_length=200, null=True)),
                ('gender', models.CharField(max_length=200, null=True)),
                ('joiningdate', models.DateField(null=True)),
                ('status', models.BooleanField(default=True)),
            ],
        ),
    ]
