# Generated by Django 4.2.1 on 2023-05-19 10:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetask',
            name='contact',
        ),
        migrations.RemoveField(
            model_name='employeetask',
            name='gender',
        ),
        migrations.AddField(
            model_name='employeetask',
            name='enddate',
            field=models.DateField(null=True),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='cat',
            field=models.IntegerField(choices=[(1, 'Office'), (2, 'Personal')], verbose_name='Category'),
        ),
        migrations.AlterField(
            model_name='employeetask',
            name='name',
            field=models.CharField(max_length=50, verbose_name='Task name'),
        ),
    ]
