# Generated by Django 4.2.1 on 2023-05-22 07:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0003_rename_enddate_employeetask_taskassigndate_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetask',
            name='taskassigndate',
        ),
        migrations.AddField(
            model_name='employeetask',
            name='date',
            field=models.DateField(null=True),
        ),
    ]
