# Generated by Django 4.2.1 on 2023-05-23 14:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('eapp', '0004_remove_employeetask_taskassigndate_employeetask_date'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='employeetask',
            name='date',
        ),
    ]
